'use client';
import {useMemo,useState} from 'react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowUpRight,BarChart3,Building2,CircleAlert,ExternalLink,Filter,Layers3,Presentation,Search,TrendingUp,WalletCards} from 'lucide-react';
import {consoleData} from '@/lib/console-data';
const compact=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',notation:'compact',maximumFractionDigits:1}).format(v);
const full=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
const percent=(v:number,b:number)=>b?`${(v/b*100).toFixed(1)}%`:'—';
type View='overview'|'clients'|'projects';
export default function Home(){
 const [view,setView]=useState<View>('overview'),[query,setQuery]=useState(''),[industry,setIndustry]=useState('All industries'),[status,setStatus]=useState('All statuses'),[present,setPresent]=useState(false);
 const projects=consoleData.projects, clients=consoleData.clients;
 const industries=['All industries',...Array.from(new Set(projects.map(p=>p.industry))).sort()],statuses=['All statuses',...Array.from(new Set(projects.map(p=>p.status))).sort()];
 const projectRows=useMemo(()=>projects.filter(p=>(industry==='All industries'||p.industry===industry)&&(status==='All statuses'||p.status===status)&&`${p.client} ${p.project} ${p.owner}`.toLowerCase().includes(query.toLowerCase())),[query,industry,status]);
 const clientRows=useMemo(()=>clients.filter(c=>c.client.toLowerCase().includes(query.toLowerCase())),[query]);
 const totalRevenue=clients.reduce((s,c)=>s+c.totalRevenue,0),totalCost=clients.reduce((s,c)=>s+c.totalCost,0),margin=totalRevenue-totalCost;
 const streams=[{name:'Project',value:clients.reduce((s,c)=>s+c.projectRevenue,0)},{name:'WhatsApp',value:clients.reduce((s,c)=>s+c.waRevenue,0)},{name:'RCS',value:clients.reduce((s,c)=>s+c.rcsRevenue,0)}],colors=['#35c6b4','#5d85ff','#ffbd59'];
 return <main className={present?'present app':'app'}><aside><div className="brand"><i><BarChart3/></i><div><b>MarginOS</b><small>Management console</small></div></div><nav><button onClick={()=>setView('overview')} className={view==='overview'?'on':''}><Layers3/>Overview</button><button onClick={()=>setView('clients')} className={view==='clients'?'on':''}><Building2/>Clients</button><button onClick={()=>setView('projects')} className={view==='projects'?'on':''}><WalletCards/>Projects</button></nav><div className="source"><span>Verified source</span><b>Chatbot Projects</b><small>Snapshot · {consoleData.asOf}</small><a href={consoleData.sourceUrl} target="_blank">Open Google Sheet <ExternalLink/></a></div></aside>
 <section className="workspace"><header><div><p>Commercial intelligence</p><h1>{view==='overview'?'Executive overview':view==='clients'?'Client profitability':'Project portfolio'}</h1></div><div className="actions"><button onClick={()=>setPresent(!present)}><Presentation/>{present?'Exit':'Present'}</button><a href={consoleData.sourceUrl} target="_blank">Source data <ArrowUpRight/></a></div></header>
 <div className="filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search client, project or owner…"/></label>{view==='projects'&&<><label><Filter/><select value={industry} onChange={e=>setIndustry(e.target.value)}>{industries.map(x=><option key={x}>{x}</option>)}</select></label><label><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label></>}<span>Project commercials + WA + RCS</span></div>
 {view==='overview'?<div className="content"><div className="kpis"><Kpi label="Total revenue" value={compact(totalRevenue)} note="Across 3 streams" icon={<TrendingUp/>}/><Kpi label="Gross margin" value={compact(margin)} note={percent(margin,totalRevenue)+' blended'} icon={<WalletCards/>}/><Kpi label="Live projects" value={String(projects.filter(p=>p.status==='Live').length)} note={projects.length+' total projects'} icon={<Layers3/>}/><Kpi label="Clients at risk" value={String(clients.filter(c=>c.margin<0).length)} note="Negative margin" icon={<CircleAlert/>}/></div>
 <div className="grid"><Card title="Revenue & margin trajectory" sub="Monthly consumables performance"><div className="chart"><ResponsiveContainer><AreaChart data={consoleData.monthly}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#5d85ff" stopOpacity=".35"/><stop offset="1" stopColor="#5d85ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9edf3"/><XAxis dataKey="month" tickFormatter={x=>new Date(x+'-01').toLocaleDateString('en-IN',{month:'short'})}/><YAxis tickFormatter={compact}/><Tooltip formatter={v=>full(Number(v))}/><Area dataKey="waRevenue" name="WA revenue" stroke="#5d85ff" fill="url(#fill)" strokeWidth={3}/><Area dataKey="waMargin" name="WA margin" stroke="#35c6b4" fill="transparent" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Card>
 <Card title="Commercial mix" sub="Revenue by stream"><div className="donut"><ResponsiveContainer><PieChart><Pie data={streams} dataKey="value" innerRadius={55} outerRadius={80} paddingAngle={4}>{streams.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip formatter={v=>full(Number(v))}/></PieChart></ResponsiveContainer><strong>{percent(streams[1].value,totalRevenue)}<small>WA share</small></strong></div><div className="legend">{streams.map((x,i)=><div key={x.name}><i style={{background:colors[i]}}/><b>{x.name}</b><span>{compact(x.value)}</span></div>)}</div></Card>
 <Card title="Portfolio movement" sub="Projects by current status"><div className="chart"><ResponsiveContainer><BarChart data={consoleData.statuses.slice(0,7)} layout="vertical"><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={90} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="value" radius={[0,7,7,0]}>{consoleData.statuses.slice(0,7).map((_,i)=><Cell key={i} fill={i===0?'#35c6b4':'#9aa7bb'}/>)}</Bar></BarChart></ResponsiveContainer></div></Card>
 <Card title="Top client contribution" sub="Ranked by total revenue"><div className="ranks">{clients.slice(0,8).map((c,i)=><div key={c.client}><em>{String(i+1).padStart(2,'0')}</em><p><b>{c.client}</b><small>{c.projects} projects · {percent(c.margin,c.totalRevenue)} margin</small></p><strong>{compact(c.totalRevenue)}</strong></div>)}</div></Card></div></div>:view==='clients'?<ClientTable rows={clientRows}/>:<ProjectTable rows={projectRows}/>}
 </section></main>
}
function Kpi({label,value,note,icon}:{label:string,value:string,note:string,icon:React.ReactNode}){return <article className="kpi"><i>{icon}</i><span>{label}</span><b>{value}</b><small>{note}</small></article>}
function Card({title,sub,children}:{title:string,sub:string,children:React.ReactNode}){return <article className="card"><div className="title"><h2>{title}<small>{sub}</small></h2><button>•••</button></div>{children}</article>}
function ClientTable({rows}:{rows:typeof consoleData.clients}){return <div className="content tableview"><div className="heading"><div><h2>Client 360 profitability</h2><p>Project commercials, WhatsApp and RCS contribution.</p></div><span>{rows.length} clients</span></div><div className="table"><table><thead><tr><th>Client</th><th>Projects</th><th>Project</th><th>WhatsApp</th><th>RCS</th><th>Total revenue</th><th>Total margin</th><th>Margin %</th></tr></thead><tbody>{rows.slice(0,120).map(c=><tr key={c.client}><td><b>{c.client}</b><small>{c.live} live</small></td><td>{c.projects}</td><td>{compact(c.projectRevenue)}</td><td>{compact(c.waRevenue)}</td><td>{compact(c.rcsRevenue)}</td><td><b>{compact(c.totalRevenue)}</b></td><td className={c.margin<0?'bad':'good'}>{compact(c.margin)}</td><td><span className={c.margin<0?'pill bad':c.margin/c.totalRevenue<.08?'pill warn':'pill good'}>{percent(c.margin,c.totalRevenue)}</span></td></tr>)}</tbody></table></div></div>}
function ProjectTable({rows}:{rows:typeof consoleData.projects}){return <div className="content tableview"><div className="heading"><div><h2>Project commercial portfolio</h2><p>Delivery context with contracted revenue, cost and margin.</p></div><span>{rows.length} projects</span></div><div className="table"><table><thead><tr><th>Project & client</th><th>Industry</th><th>Owner</th><th>Vendor</th><th>Status</th><th>Revenue</th><th>Cost</th><th>Margin</th></tr></thead><tbody>{rows.map(p=><tr key={p.client+p.project}><td><b>{p.project}</b><small>{p.client}</small></td><td>{p.industry}</td><td>{p.owner}</td><td>{p.vendor}</td><td><span className={'status '+p.status.toLowerCase().replaceAll(' ','-')}>{p.status}</span></td><td>{compact(p.revenue)}</td><td>{compact(p.cost)}</td><td className={p.margin<0?'bad':'good'}>{compact(p.margin)}</td></tr>)}</tbody></table></div></div>}
