const START='2026-04',HORIZON=6;
const clean=(v:unknown)=>String(v??'').trim();
const num=(v:unknown)=>Number(clean(v).replace(/[₹,$%\s]/g,'').replace(/\((.*)\)/,'-$1'))||0;
const hk=(v:unknown)=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const rk=(v:unknown)=>hk(v).replace(/\s+/g,'');
// The source tabs do not always use the identical legal-name suffix.  Use one
// stable key for joins, but retain the first source label for display.
const clientKey=(v:unknown)=>hk(v).replace(/\b(private|pvt|limited|ltd|company|co)\b/g,'').replace(/\s+/g,'');
const col=(h:string[],names:string[])=>{const w=names.map(hk);return h.findIndex(x=>w.includes(hk(x)))};

export function parseCsv(text:string){
 const rows:string[][]=[];let row:string[]=[],field='',quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field=''}else field+=c}
 row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows;
}
function monthValue(value:string){
 const v=clean(value);if(/^\d{4}-\d{2}/.test(v))return v.slice(0,7);
 const shortMonth=v.match(/^([A-Za-z]{3})[\s-](\d{2}|\d{4})$/);if(shortMonth){const names=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'],m=names.indexOf(shortMonth[1].toLowerCase()),rawYear=Number(shortMonth[2]),y=rawYear<100?2000+rawYear:rawYear;if(m>=0)return `${y}-${String(m+1).padStart(2,'0')}`}
 const indian=v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(indian){const m=+indian[2],y=+indian[3];if(m>0&&m<13)return `${y}-${String(m).padStart(2,'0')}`}
 const d=new Date(v);if(!Number.isNaN(d.getTime()))return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
 const serial=Number(v);if(serial>30000){const x=new Date(Date.UTC(1899,11,30)+serial*86400000);return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,'0')}`}return '';
}
function plusMonth(month:string,n:number){const [y,m]=month.split('-').map(Number),d=new Date(y,m-1+n,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
type Monthly={client:string;month:string;chatbotRevenue:number;chatbotCost:number;waRevenue:number;waCost:number;rcsRevenue:number;rcsCost:number;periodType:'Actual'|'Forecast'};
const empty=(client:string,month:string,periodType:'Actual'|'Forecast'='Actual'):Monthly=>({client,month,chatbotRevenue:0,chatbotCost:0,waRevenue:0,waCost:0,rcsRevenue:0,rcsCost:0,periodType});

export function buildDashboard(projectCsv:string,rmCsv:string,waCsv:string,rcsCsv:string,sourceUrl:string){
 const p=parseCsv(projectCsv),rm=parseCsv(rmCsv),wa=parseCsv(waCsv),rcs=parseCsv(rcsCsv);if(p.length<2)throw new Error('Chatbot Projects CSV has no data rows.');
 const pi=p.findIndex(r=>r.some(v=>hk(v)==='chatbot'));if(pi<0)throw new Error('Chatbot Projects is missing its named header row.');
 const ph=p[pi],pcClient=col(ph,['Client Legal Name','Client','Client Name']),pcProject=col(ph,['Chatbot','Project','Project Name']),pcIndustry=col(ph,['Industry']),pcOwner=col(ph,['Sales Connect','Owner','Project Owner']),pcType=col(ph,['Bot Type','Type']),pcVendor=col(ph,['Vendor']),pcStatus=col(ph,['Status','Stage']);
 if([pcClient,pcProject,pcStatus].some(i=>i<0))throw new Error('Chatbot Projects is missing a required named column.');
 const projects=p.slice(pi+1).filter(r=>clean(r[pcClient])||clean(r[pcProject])).map(r=>({client:clean(r[pcClient]),project:clean(r[pcProject]),industry:pcIndustry>=0?clean(r[pcIndustry])||'Unclassified':'Unclassified',owner:pcOwner>=0?clean(r[pcOwner])||'Unassigned':'Unassigned',type:pcType>=0?clean(r[pcType])||'Unspecified':'Unspecified',vendor:pcVendor>=0?clean(r[pcVendor])||'Unspecified':'Unspecified',status:clean(r[pcStatus])||'Unspecified',revenue:0,cost:0,margin:0}));
 const clientLabels=new Map<string,string>();
 const resolveClient=(value:unknown,fallback='')=>{const label=clean(value)||fallback,key=clientKey(label);if(!key)return label;const known=clientLabels.get(key);if(known)return known;clientLabels.set(key,label);return label};
 projects.forEach(project=>{project.client=resolveClient(project.client,project.project)});
 const now=new Date(),current=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,future=Array.from({length:HORIZON},(_,i)=>plusMonth(current,i+1)),last=future.at(-1)!;
 const projectByBot=new Map<string,any[]>();projects.forEach(x=>{const key=rk(x.project),list=projectByBot.get(key)||[];list.push(x);projectByBot.set(key,list)});
 const resolveProject=(bot:string)=>{const key=rk(bot),exact=projectByBot.get(key)||[];if(exact.length===1)return exact[0];const fuzzy=projects.filter(x=>{const candidate=rk(x.project);return key.length>5&&candidate.length>5&&(candidate.includes(key)||key.includes(candidate))});return fuzzy.length===1?fuzzy[0]:null};
 const actual=new Map<string,Monthly>(),forecast=new Map<string,Monthly>(),projectTotals=new Map<string,{revenue:number;cost:number}>(),latest=new Map<string,{client:string;month:string;revenue:number;cost:number}>(),explicit=new Set<string>(),liveKeys=new Set(projects.filter(x=>hk(x.status)==='live').map(x=>rk(x.project)));
 const ri=rm.findIndex(r=>r.some(v=>hk(v)==='chatbot')&&r.some(v=>hk(v)==='month'));
 if(ri>=0){const h=rm[ri],cc=col(h,['Client','Client Name','Client Legal Name']),cb=col(h,['Chatbot','Project','Project Name']),cm=col(h,['Month','Billing Month','Revenue Month']),cr=col(h,['Total Netcore Revenue','Netcore Total Revenue','Total Revenue Netcore','Total Revenue','Monthly Revenue','Revenue']),co=col(h,['Total Vendor Cost','Vendor Total Cost','Total Cost Vendor','Total Cost','Vendor Cost','Cost']);if([cb,cm,cr,co].some(i=>i<0))throw new Error('Chatbot R&M is missing a required named financial column.');
  rm.slice(ri+1).forEach(r=>{const bot=clean(r[cb]),matched=resolveProject(bot),client=resolveClient((cc>=0?clean(r[cc]):'')||matched?.client||'',matched?.project||bot),month=monthValue(r[cm]);if(!client||!bot||!month||month<START)return;const revenue=num(r[cr]),cost=num(r[co]);if(!revenue&&!cost)return;const bk=rk(matched?.project||bot);
   if(month<=current){const key=client+'\u0000'+month,x=actual.get(key)||empty(client,month);x.chatbotRevenue+=revenue;x.chatbotCost+=cost;actual.set(key,x);const t=projectTotals.get(bk)||{revenue:0,cost:0};t.revenue+=revenue;t.cost+=cost;projectTotals.set(bk,t);const old=latest.get(bk);if(!old||month>old.month)latest.set(bk,{client,month,revenue,cost});}
   else if(month<=last&&liveKeys.has(bk)){const key=client+'\u0000'+month,x=forecast.get(key)||empty(client,month,'Forecast');x.chatbotRevenue+=revenue;x.chatbotCost+=cost;forecast.set(key,x);explicit.add(bk+'\u0000'+month);}
  });
 }
 projects.forEach(p=>{const key=rk(p.project);let f=projectTotals.get(key);if(!f){const matches=[...projectTotals.entries()].filter(([candidate])=>key.length>5&&candidate.length>5&&(candidate.includes(key)||key.includes(candidate)));if(matches.length===1)f=matches[0][1]}if(f){p.revenue=f.revenue;p.cost=f.cost;p.margin=f.revenue-f.cost}});
 projects.filter(p=>hk(p.status)==='live').forEach(p=>{const bk=rk(p.project),run=latest.get(bk);if(!run)return;future.forEach(month=>{if(explicit.has(bk+'\u0000'+month))return;const client=p.client||run.client,key=client+'\u0000'+month,x=forecast.get(key)||empty(client,month,'Forecast');x.chatbotRevenue+=run.revenue;x.chatbotCost+=run.cost;forecast.set(key,x)})});

 const addUsage=(rows:string[][],kind:'wa'|'rcs')=>{const i=rows.findIndex(r=>r.some(v=>['client','client name','client legal name'].includes(hk(v)))&&r.some(v=>hk(v)==='month'));if(i<0)return;const h=rows[i],cc=col(h,['Client','Client Name','Client Legal Name']),cm=col(h,['Month','Billing Month','Revenue Month']),cr=col(h,['Revenue','Total Revenue','Monthly Revenue']),co=col(h,['Cost','Total Cost','Monthly Cost']);if([cc,cm,cr,co].some(x=>x<0))return;rows.slice(i+1).forEach(r=>{const client=resolveClient(r[cc]),month=monthValue(r[cm]);if(!client||!month||month<START||month>current)return;const key=client+'\u0000'+month,x=actual.get(key)||empty(client,month);if(kind==='wa'){x.waRevenue+=num(r[cr]);x.waCost+=num(r[co])}else{x.rcsRevenue+=num(r[cr]);x.rcsCost+=num(r[co])}actual.set(key,x)})};
 addUsage(wa,'wa');addUsage(rcs,'rcs');
 const actualRows=[...actual.values()],waMonths=[...new Set(actualRows.filter(x=>x.waRevenue||x.waCost).map(x=>x.month))].sort().reverse().slice(0,3),rcsMonths=[...new Set(actualRows.filter(x=>x.rcsRevenue||x.rcsCost).map(x=>x.month))].sort().reverse().slice(0,3),waDivisor=Math.max(1,waMonths.length),rcsDivisor=Math.max(1,rcsMonths.length);new Set(actualRows.map(x=>x.client)).forEach(client=>{const waHistory=actualRows.filter(x=>x.client===client&&waMonths.includes(x.month)),rcsHistory=actualRows.filter(x=>x.client===client&&rcsMonths.includes(x.month));if(!waHistory.length&&!rcsHistory.length)return;const waRate=waHistory.reduce((a,x)=>({revenue:a.revenue+x.waRevenue,cost:a.cost+x.waCost}),{revenue:0,cost:0}),rcsRate=rcsHistory.reduce((a,x)=>({revenue:a.revenue+x.rcsRevenue,cost:a.cost+x.rcsCost}),{revenue:0,cost:0});future.forEach(month=>{const key=client+'\u0000'+month,x=forecast.get(key)||empty(client,month,'Forecast');x.waRevenue+=waRate.revenue/waDivisor;x.waCost+=waRate.cost/waDivisor;x.rcsRevenue+=rcsRate.revenue/rcsDivisor;x.rcsCost+=rcsRate.cost/rcsDivisor;forecast.set(key,x)})});
 const clientMonthly=[...actual.values()].sort((a,b)=>a.month.localeCompare(b.month)||a.client.localeCompare(b.client)),forecastClientMonthly=[...forecast.values()].sort((a,b)=>a.month.localeCompare(b.month)||a.client.localeCompare(b.client));
 const clientMap=new Map<string,any>();for(const x of projects){const c=clientMap.get(x.client)||{client:x.client,projectRevenue:0,projectCost:0,waRevenue:0,waCost:0,rcsRevenue:0,rcsCost:0,projects:0,live:0};c.projectRevenue+=x.revenue;c.projectCost+=x.cost;c.projects++;if(hk(x.status)==='live')c.live++;clientMap.set(x.client,c)}for(const x of clientMonthly){const c=clientMap.get(x.client)||{client:x.client,projectRevenue:0,projectCost:0,waRevenue:0,waCost:0,rcsRevenue:0,rcsCost:0,projects:0,live:0};c.waRevenue+=x.waRevenue;c.waCost+=x.waCost;c.rcsRevenue+=x.rcsRevenue;c.rcsCost+=x.rcsCost;clientMap.set(x.client,c)}
 const clients=[...clientMap.values()].map(c=>({...c,totalRevenue:c.projectRevenue+c.waRevenue+c.rcsRevenue,totalCost:c.projectCost+c.waCost+c.rcsCost,margin:c.projectRevenue+c.waRevenue+c.rcsRevenue-c.projectCost-c.waCost-c.rcsCost})).sort((a,b)=>b.totalRevenue-a.totalRevenue);
 const months=[...new Set(clientMonthly.map(x=>x.month))].sort(),monthly=months.map(month=>clientMonthly.filter(x=>x.month===month).reduce((a,x)=>({...a,chatbotRevenue:a.chatbotRevenue+x.chatbotRevenue,chatbotMargin:a.chatbotMargin+x.chatbotRevenue-x.chatbotCost,waRevenue:a.waRevenue+x.waRevenue,waMargin:a.waMargin+x.waRevenue-x.waCost,rcsRevenue:a.rcsRevenue+x.rcsRevenue,rcsMargin:a.rcsMargin+x.rcsRevenue-x.rcsCost}),{month,chatbotRevenue:0,chatbotMargin:0,waRevenue:0,waMargin:0,rcsRevenue:0,rcsMargin:0}));
 const statuses=[...projects.reduce((m,x)=>m.set(x.status,(m.get(x.status)||0)+1),new Map<string,number>())].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);
 const forecastMonthly=future.map(month=>forecastClientMonthly.filter(x=>x.month===month).reduce((a,x)=>({...a,chatbotRevenue:a.chatbotRevenue+x.chatbotRevenue,chatbotCost:a.chatbotCost+x.chatbotCost,waRevenue:a.waRevenue+x.waRevenue,waCost:a.waCost+x.waCost,rcsRevenue:a.rcsRevenue+x.rcsRevenue,rcsCost:a.rcsCost+x.rcsCost,totalRevenue:a.totalRevenue+x.chatbotRevenue+x.waRevenue+x.rcsRevenue,totalCost:a.totalCost+x.chatbotCost+x.waCost+x.rcsCost}),{month,periodType:'Forecast' as const,chatbotRevenue:0,chatbotCost:0,waRevenue:0,waCost:0,rcsRevenue:0,rcsCost:0,totalRevenue:0,totalCost:0}));
 return {consoleData:{asOf:new Date().toISOString().slice(0,10),reportingStart:START,sourceUrl,clients,projects,monthly,statuses,forecastMonthly},clientMonthly,forecastClientMonthly};
}
